### ISSUE TITLE
Problem "connecting" to cuDNN library

### ISSUE THREAD

**Issue by rmurray2** [andersbll/neural_artistic_style#16]
Greetings, 

Getting this error when running the example:

`terminate called after throwing an instance of 'std::runtime_error'
  what():  ./include/cudarray/nnet/cudnn.hpp:107: The cuDNN library was not initialized properly.
Aborted
`
I made sure the `CUDNN_ENABLED` was set to `1` when building `cudarray`; did not see any messages indicated a problem 'connecting' to cuDNN  during that step.

I obtained cuDNN from Nvidia (cudnn-7.0-linux-x64-v3.0-prod.tgz) and moved the contents in the following way:

`sudo cp cudnn.h /opt/nvidia/cuda/include`
`sudo cp libcudnn* /opt/nvidia/cuda/lib`

Any idea what the problem could be?

**Comment by andersbll** [comment]
Hi there!

What's the version of your CUDA SDK? Maybe it's a version mismatch.

BTW: you can run the script without cuDNN if you use `--pool-method max`. Average pooling is only implemented in the cuDNN backend.

**Comment by rmurray2** [comment]
Greetings; I think you're correct about the version mismatch:

```
[ec2-user@ip-172-31-3-36 ~]$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2014 NVIDIA Corporation
Built on Thu_Jul_17_21:41:27_CDT_2014
Cuda compilation tools, release 6.5, V6.5.12
```

And the version of cuDNN I obtained has the note:
`Download cuDNN v3 (September 8, 2015), for CUDA 7.0 and later.`

Strangely, when I installed cuDNN v2 and tried to build `cudarray`, I got the error:

```
[ec2-user@ip-172-31-3-36 cudarray-master]$ make
g++ -DCUDNN_ENABLED -O3 -fPIC -Wall -Wfatal-errors -I./include -I/opt/nvidia/cuda//include -c -o src/nnet/conv_bc01_matmul.o src/nnet/conv_bc01_matmul.cpp
nvcc -gencode arch=compute_20,code=sm_20 -gencode arch=compute_20,code=compute_20 -gencode arch=compute_30,code=sm_30 -gencode arch=compute_30,code=compute_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_35,code=compute_35 -O3 --compiler-options '-DCUDNN_ENABLED -O3 -fPIC -Wall -Wfatal-errors' --ftz=true --prec-div=false -prec-sqrt=false --fmad=true -I./include -I/opt/nvidia/cuda//include -c -o src/nnet/pool_b01.o src/nnet/pool_b01.cu
g++ -DCUDNN_ENABLED -O3 -fPIC -Wall -Wfatal-errors -I./include -I/opt/nvidia/cuda//include -c -o src/nnet/cudnn.o src/nnet/cudnn.cpp
In file included from src/nnet/cudnn.cpp:5:0:
./include/cudarray/nnet/cudnn.hpp:35:3: error: ‘cudnnTensorDescriptor_t’ does not name a type
   cudnnTensorDescriptor_t imgs_desc;
   ^
compilation terminated due to -Wfatal-errors.
make: *** [src/nnet/cudnn.o] Error 1
```

Anyway, upon specifying `--pool-method max`, the efficiency gain was enormous relative to a CPU without a CUDA backend - so I am content. If you would like to see this issue resolved with a documented answer, however, I can try to go back and see if I can get it to work (do you have any other suggestions?) but for my purposes I'm happy with just using `--pool-method max`.

Out of curiosity, what differences are there with specifying average pooling?

**Comment by andersbll** [comment]
CUDArray only supports cuDNNv3. You should update your CUDA SDK instead.

Also: I have recently added average pooling to CUDArray. If you pull the recent version you won't need cuDNN. :)
